version: "3.8"
services:
  hello-world:
    container_name: hello-world
    image: hello-world
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      BPL_DEBUG_ENABLED: "true"
      BPL_DEBUG_PORT: 9090
