apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: hello-world-java
build:
  artifacts:
  - image: hello-world
    jib: { }

manifests:
  rawYaml:
    - config/temporal-worker-configmap.yml
    - config/hello-world.yml
    - config/temporal-worker.yml
    - config/maru.yml

deploy:
  kubectl: { }

portForward:
  - resourceType: service
    resourceName: temporal-web
    namespace: temporal
    port: 8088
    localPort: 8088