apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: hello-world-java
build:
  artifacts:
  - image: hello-world
    jib: { }

manifests:
  rawYaml:
  - config/hello-world.yml
  - config/temporal-worker.yml

portForward:
  - resourceType: service
    resourceName: temporal-hello-world-web
    namespace: default
    port: 8080
    localPort: 9000