temporal:
  server:
    hostname: temporal.temporal.svc.cluster.local
    port: 7233
    url: "${temporal.server.hostname}:${temporal.server.port}"
  workflow:
    taskqueue: MAIN_TASK_QUEUE
    id: HelloActivityWorkflow

