apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-worker
  labels:
    app: temporal-worker
spec:
  selector:
    matchLabels:
      app: temporal-worker
  progressDeadlineSeconds: 60
  template:
    metadata:
      labels:
        app: temporal-worker
    spec:
      containers:
        - name: temporal-worker
          image: hello-world
          ports:
            - containerPort: 8081
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: temporal-worker-configmap
                  key: port
            - name: WORKER
              valueFrom:
                configMapKeyRef:
                  name: temporal-worker-configmap
                  key: worker
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-worker
spec:
  type: NodePort
  ports:
    - port: 8081
  selector:
    app: temporal-worker